### PR TITLE
Navigation bar

### PR DESCRIPTION
**Pull request by MrTheGood**
Changes:
 * Added working bottom navigation bar
 * Added colours
 * Added required fragments

How to test: 
 1. Run app
 2. Verify that clicking settings, map, search and memories works correctly
 3. Ignore that add memory doesn't work correctly

Screenshots:
map
memories
search
settings

### CODE REVIEW

**Comment by MrTheGood** [comment]
Please check the code when reviewing it, and ask about anything you don't understand.

**Comment by AnassM06** [comment]
Good job !

**Comment by Almightywesley** [comment]
Looks nice!\

**Comment by Hicham010** [comment]
goed gedaan pik!!!

**Review by Almightywesley — APPROVED** [review]

**Review by AnassM06 — APPROVED** [review]

**Review by Hicham010 — APPROVED** [review]
nice!!!!

**Review by HenkvanAsperen — COMMENTED** [review]
Nais man

**Review by HenkvanAsperen — APPROVED** [review]
nais man

**Pull request merged**
