### PR TITLE
Onboarding

### PR DESCRIPTION
**Pull request by MrTheGood**
### Changes:
 * Added some cool red themes because why tf not
 * Added onboarding page that is shown on first startup
 * Onboarding can be restarted by a button in the settings page
 * Some code cleanup

### How to test: 
 1. **Test** the Light Red and Dark Red themes
 2. **Confirm** if the onboarding page is correctly shown on first run
 3. **Confirm** that it does not show up after skip or finish
 4. **Confirm** that it looks how it should look on **your phone**

### Screenshots:
**Onboarding page**
device-2019-05-22-223342
device-2019-05-22-223350
**Light Red theme**
device-2019-05-22-223430
**Dark Red theme**
device-2019-05-22-223442
**Onboarding page in Dark Red theme**
device-2019-05-22-223549
device-2019-05-22-223555

### CODE REVIEW

**Comment by MrTheGood** [comment]
### Update: I just added the tooltip on the `MapFragment`
It is shown until closed by clicking the close button or swiping it away (aka `fling`ing it).
It's shown again if the tutorial is reset in the `SettingsFragment`

device-2019-05-22-233523

**Comment by Almightywesley** [comment]
cool will test later

**Comment by Almightywesley** [comment]
what did i do?

**Review by Hicham010 — APPROVED** [review]
Nicely done Mr.thegood

**Review by Almightywesley — CHANGES_REQUESTED** [review]
I want to see dots to indicate howmany slides there are

**Review by Almightywesley — APPROVED** [review]
I see that you implemented the feedback i gave you, noice job!

**Pull request merged**
