### PR TITLE
Share feature

### PR DESCRIPTION
**Pull request by Hicham010**
I implemented the feedback you all gave me.

The share feature now allows share images with text.

### CODE REVIEW

**Comment by MrTheGood** [comment]
I tried to revert a code change, but this is too many issues.

**Comment by MrTheGood** [comment]
Fixed it, but haven't tested it.

**Review by MrTheGood — CHANGES_REQUESTED** [review]
Code looks fine. Can someone else please verify that it works?

**Review by Almightywesley — APPROVED** [review]
Whats app sharing works nice

**Review by MrTheGood — APPROVED** [review]

**Pull request merged**
