### PR TITLE
Memory detail

### PR DESCRIPTION
**Pull request by Hicham010**
Changes:
 * Added this amazing feature
 * Fixed bug where thing happened instead of thing
 * Improved this feature
I added the memory details, lol.

How to test: 
 1. Do this
 2. Then do this

Screenshots:
If applicable, add a screenshot or video here to show the new feature

### CODE REVIEW

**Review by AnassM06 — APPROVED** [review]
looks good

**Review by MrTheGood — COMMENTED** [review]
I made the alert dialog more readable. I'll run the app before approving.

**Comment by MrTheGood** [comment]
The pull request message could be better, though.

**Comment by MrTheGood** [comment]
The toolbar is a bit weird, but otherwise it's fine. Approved.

**Review by MrTheGood — APPROVED** [review]

**Pull request merged**
