### PR TITLE
Password

### PR DESCRIPTION
**Pull request by MrTheGood**
Changes:
 * You can use password protected mode
 * If you have Android Oreo you can use fingerprint scanner

### CODE REVIEW

**Review by Almightywesley — CHANGES_REQUESTED** [review]
nice work but,
Rigth now its to easy to change someones password and lock them out forever, maybe make the user type in his own password before he can change his password.

**Review by Almightywesley — CHANGES_REQUESTED** [review]
nice

**Comment by Hicham010** [comment]
> nice work but,
> Rigth now its to easy to change someones password and lock them out forever, maybe make the user type in his own password before he can change his password.

Yes, I also wanted to point that out. Please change this.

**Review by Almightywesley — APPROVED** [review]
i see that you have implemented the feedback i gave you nice work

**Comment by Hicham010** [comment]
To change the current password you don't need to fill in the current password in the editText. You can leave it blank or fill in a false password and you can still change the password.

**Review by Hicham010 — APPROVED** [review]

**Pull request merged**
