### PR TITLE
Sqlite database

### PR DESCRIPTION
**Pull request by MrTheGood**
Changes:
 * Added SQLite database
 * Added deleteMemory to Database
 * Added updateMemory to Database
 * Memories now store images and videos as string path. 

How to test: 
 1. Run the app and make sure that content is added correctly when adding new memories.
 2. Read the code and try to understand the basics
      info about Room (used library): https://developer.android.com/training/data-storage/room/index.html
      also: https://codelabs.developers.google.com/codelabs/android-room-with-a-view/#0
 3. It's okay if you don't understand. The only thing you'll most likely deal with is the Database class and the Memory, Video and Image classes. 
 4. Do ask questions if you don't understand, however.

### CODE REVIEW

**Comment by Hicham010** [comment]
Maarten, ik zou toch de delete Memory en edit/update Memory doen.

**Comment by MrTheGood** [comment]
@Hicham010 de database moet dat wel supporten

**Review by Hicham010 — APPROVED** [review]
Nice work mate

**Review by AnassM06 — APPROVED** [review]
looks good

**Pull request merged**
