### PR TITLE
I added the memory detail activity, and completed all the trello tasks.

### PR DESCRIPTION
**Pull request by Hicham010**
Changes:
share button and delete button.
scrolling
pageview2

How to test: 
 1. Do this
 2. Then do this

Screenshots:
If applicable, add a screenshot or video here to show the new feature

### CODE REVIEW

**Review by AnassM06 — APPROVED** [review]
looks good

**Review by Almightywesley — APPROVED** [review]
Very nice it works!

**Comment by MrTheGood** [comment]
The code looks good. The Kotlin should be converted to Java, but I'll take care of that.

**Review by MrTheGood — APPROVED** [review]
Works and code looks good! Nice work!

**Pull request merged**
