### PR TITLE
Fix #51

### LINKED ISSUE #51: [BUG] Date text editable
**Describe the bug**
The date input on EditMemoryActivity is editable. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Open EditMemoryActivity
2. Click the date input
3. Cancel the dialog
4. Type whatever you want

**Expected behavior**
When you press 'cancel' or 'ok', you'd expect the next input to be selected automatically.

### PR DESCRIPTION
**Pull request by MrTheGood**
Fix #51

### CODE REVIEW

**Review by Almightywesley — APPROVED** [review]
Noice

**Comment by MrTheGood** [comment]
> Noice

I agree. Thank you for the very usefull feedback.

**Review by Hicham010 — APPROVED** [review]
I see you implemented my feedback, nice work knaap.

**Comment by MrTheGood** [comment]
> I see you implemented my feedback, nice work knaap.

No problem. You gave very usefull feedback. <3

**Pull request merged**
