### PR TITLE
Mapview

### PR DESCRIPTION
**Pull request by Almightywesley**
Changes:
 * Added this amazing feature
 * Fixed bug where thing happened instead of thing
 * Improved this feature

How to test: 
 1. Do this
open the app and see the pointers
 2. Then do this
look at it

Screenshots:
If applicable, add a screenshot or video here to show the new feature

### CODE REVIEW

**Review by MrTheGood — COMMENTED** [review]
An API key should not be added to git, but since this is a free key anyway we can safely ignore it. 
I'll undo the removing of the .idea files and after that it's good.

**Review by AnassM06 — DISMISSED** [review]
Looks good

**Review by MrTheGood — CHANGES_REQUESTED** [review]
App crashes on startup.

**Comment by MrTheGood** [comment]
```2019-03-26 11:40:49.887 27700-27726/nl.hogeschoolrotterdam.projectb E/AndroidRuntime: FATAL EXCEPTION: Thread-3
    Process: nl.hogeschoolrotterdam.projectb, PID: 27700
    java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/ProtocolVersion;
        at fb.b(:com.google.android.gms.dynamite_mapsdynamite@15181084@15.1.81 (100700-239627737):3)
        at fa.a(:com.google.android.gms.dynamite_mapsdynamite@15181084@15.1.81 (100700-239627737):3)
        at fc.a(:com.google.android.gms.dynamite_mapsdynamite@15181084@15.1.81 (100700-239627737):15)
        at com.google.maps.api.android.lib6.drd.al.a(:com.google.android.gms.dynamite_mapsdynamite@15181084@15.1.81 (100700-239627737):6)
        at ee.a(:com.google.android.gms.dynamite_mapsdynamite@15181084@15.1.81 (100700-239627737):23)
        at ee.run(:com.google.android.gms.dynamite_mapsdynamite@15181084@15.1.81 (100700-239627737):8)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.ProtocolVersion" on path: DexPathList[[zip file "/data/user_de/0/com.google.android.gms/app_chimera/m/00000016/MapsDynamite.apk"],nativeLibraryDirectories=[/data/user_de/0/com.google.android.gms/app_chimera/m/00000016/MapsDynamite.apk!/lib/x86, /system/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:195)
        at dalvik.system.DelegateLastClassLoader.loadClass(DelegateLastClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at fb.b(:com.google.android.gms.dynamite_mapsdynamite@15181084@15.1.81 (100700-239627737):3) 
        at fa.a(:com.google.android.gms.dynamite_mapsdynamite@15181084@15.1.81 (100700-239627737):3) 
        at fc.a(:com.google.android.gms.dynamite_mapsdynamite@15181084@15.1.81 (100700-239627737):15) 
        at com.google.maps.api.android.lib6.drd.al.a(:com.google.android.gms.dynamite_mapsdynamite@15181084@15.1.81 (100700-239627737):6) 
        at ee.a(:com.google.android.gms.dynamite_mapsdynamite@15181084@15.1.81 (100700-239627737):23) 
        at ee.run(:com.google.android.gms.dynamite_mapsdynamite@15181084@15.1.81 (100700-239627737):8) 
```

**Review by MrTheGood — APPROVED** [review]
Looks good. MapView location should not be reset on navigation, though.

**Review by AnassM06 — APPROVED** [review]
runs now without crashing looks good

**Pull request merged**
