### PR TITLE
Sort memory by date

### PR DESCRIPTION
**Pull request by AnassM06**
Changes:
 *sort by newest oldest alphabetical

How to test: 
sort them 

Screenshots:
If applicable, add a screenshot or video here to show the new feature

### CODE REVIEW

**Review by MrTheGood — CHANGES_REQUESTED** [review]
This PR contains changes from a different PR.

**Review by Almightywesley — APPROVED** [review]
After reviewing your code and testing your feature i can see that it works, nice job!

**Comment by MrTheGood** [comment]
And now the other PR also contains the changes in here.

**Comment by MrTheGood** [comment]
The other PR already contains the changes in this PR, so this PR doesn't make sense anymore.

**Pull request closed without merging**
